In [1]:
import torch
from pytorch_transformers import *

model_class = BertModel
tokenizer_class = BertTokenizer
pretrained_weights = 'bert-base-uncased'

# Load pretrained model/tokenizer
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)

# Encode text
input_ids = torch.tensor([tokenizer.encode("Here is some text to encode", add_special_tokens=True)])
last_hidden_states = model(input_ids)[0][0]

print(last_hidden_states)

100%|██████████| 440473133/440473133 [00:43<00:00, 10103150.27B/s]


tensor([[-0.0549,  0.1053, -0.1065,  ..., -0.3550,  0.0686,  0.6506],
        [-0.5759, -0.3650, -0.1383,  ..., -0.6782,  0.2092, -0.1639],
        [-0.1641, -0.5597,  0.0150,  ..., -0.1603, -0.1346,  0.6216],
        ...,
        [ 0.2448,  0.1254,  0.1587,  ..., -0.2749, -0.1163,  0.8809],
        [ 0.0481,  0.4950, -0.2827,  ..., -0.6097, -0.1212,  0.2527],
        [ 0.9046,  0.2137, -0.5897,  ...,  0.3040, -0.6172, -0.1950]],
       grad_fn=<SelectBackward>)


In [2]:
input_ids

tensor([[  101,  2182,  2003,  2070,  3793,  2000,  4372, 16044,   102]])

In [7]:
print(torch.tensor([tokenizer.encode("Here is naziah", add_special_tokens=True)]))


tensor([[ 101, 2182, 2003, 6394, 4430,  102]])


In [8]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          